-- Stored Procedure SP_ALTERARFUNCIONARIO
CREATE PROCEDURE SP_ALTERARFUNCIONARIO
    @ID UNIQUEIDENTIFIER,
    @NOME NVARCHAR(150),
    @MATRICULA NVARCHAR(6),
    @CPF NVARCHAR(11)
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE FUNCIONARIO
    SET NOME = @NOME, MATRICULA = @MATRICULA, CPF = @CPF
    WHERE ID = @ID
END
