-- Stored Procedure SP_INSERIRFUNCIONARIO
CREATE PROCEDURE SP_INSERIRFUNCIONARIO
    @NOME NVARCHAR(150),
    @MATRICULA NVARCHAR(6),
    @CPF NVARCHAR(11)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO FUNCIONARIO (ID, NOME, MATRICULA, CPF)
    VALUES (NEWID(), @NOME, @MATRICULA, @CPF)
END
